### ISSUE TITLE
Document best practices

### ISSUE THREAD

**Issue by DominicParent** [StatCan/tass-ssat#13]

**Comment by ty-desj** [comment]
I'm in agreement for what you have so far, we can discuss tabs/spaces and branch naming policy the next time we meet

**Comment by DominicParent** [comment]
Following meeting with @ty-desj:
- branch naming scheme is: type-number-summary
- tabs vs spaces: 4 spaces for indentation
- code reviews: add more people per merge when team grows (~5-6 people)

Let me know if if there's an issue with the summary above.
