### ISSUE TITLE
Read and Store Values

### ISSUE THREAD

**Issue by ty-desj** [StatCan/tass-ssat#16]

**Comment by DominicParent** [comment]
@ty-desj I've been thinking about this, and I want to create a singleton class to store the values. However, singletons should only be used as a sink, something you can push values onto (and read them back) but that you can't modify the values.

Would this fit the needs you see for "Read and Store Values" action?

**Comment by ty-desj** [comment]
@DominicParent I think that should fit our needs. An example of when this would be used is for like IDs or other values generated by whatever it is being tested (like a case number for an EQ test) that will be used later. It is something that came up quite often when testing some of our older projects with the previous version of the framework.

**Comment by DominicParent** [comment]
Perfect, I'll get going on created a singleton instance to hold this information then.

**Comment by DominicParent** [comment]
Created singleton and valuestore, along with some unittest code to make sure everything works.

Might create a value class to hold the uuid of the test case along with the values to prevent collisions. Valuestore would only hold instances of Value. More thought needed.

Need to modify valuestore to prevent the creation of values if a key already exists.

**Comment by DominicParent** [comment]
Explored a few ideas, none of them are clearly needed at this time.

Won't block the creation of values at this time either. Users might want to track some info this way, though it isn't recommended. We can explore changing the behaviour once we start implementing exception throwing and such.
