### ISSUE TITLE
Webdriver Manager GitHub API Rate Limits

### ISSUE THREAD

**Issue by ty-desj** [StatCan/tass-ssat#45]
The GitHub api that the web driver manager module downloads the geckodriver (Firefox) from has a relatively low rate limit. For current usage it is unlikely to reach that limit during normal use; however, should the limit be reached (for example by executing unit tests back to back) then a soft lock is applied until the rate limit period is reset, ~1 hour.

**Comment by ty-desj** [comment]
Perhaps a solution for this will be to check if the driver for the current version of the browser is available locally before attempting the download. We could also create a temporary folder that the drivers will be downloaded to, then use that location until execution is complete before emptying the folder to avoid build-up of excess drivers for previous versions of the browser.

In any case, this should be looked into before a 1.0 release. @DominicParent if you have any thoughts?

**Comment by ty-desj** [comment]
Further research shows this is a known issue, the webdriver manager queries the GitHub API to get the version number of the latest version of GeckoDriver, it then uses this version number to check the "cached" drivers for a matching one. In this way, if the API limit is exceeded the GeckoDriver cannot be started (even from the cached driver) since the exception interrupts it. Apparently they have a fix implemented that will be part of their next release soon. This is from an issue in the webdriver manager repo, dated roughly 3 weeks ago.

**Comment by DominicParent** [comment]
We can probably leave it as is for now, but it would be useful to add some documentation about this kind of behaviour. Since they're planning a fix for their next release, let's just keep an eye on it and wait.

Do we record the version of the webdriver used anywhere? That could be good info to have in our test report.

**Comment by ty-desj** [comment]
At this time we don't record it in the report, but we should be able to pull the version of webdriver and the browser from the webdriver manager. It is definitely something I would like to add to reporting.

**Comment by ty-desj** [comment]
The webdriver manager library has been updated and it appears they have resolved this issue. Closing this ticket as resolved.
