### ISSUE TITLE
Pip packaging script

### ISSUE THREAD

**Issue by DominicParent** [StatCan/tass-ssat#50]

**Comment by DominicParent** [comment]
Going to transform the packaging layout to a src layout. Instead of tass-ssat/tass it will be tass-ssat/src/tass. This will bring us in line with more common approaches. It will also help us use the build system.

For more reading on this:
https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html
https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#custom-discovery

**Comment by DominicParent** [comment]
We will need to use editable installs.

More reading:
- https://stackoverflow.com/questions/69711606/how-to-install-a-package-using-pip-in-editable-mode-with-pyproject-toml
- https://peps.python.org/pep-0660/
- https://setuptools.pypa.io/en/latest/userguide/development_mode.html

**Comment by DominicParent** [comment]
@ty-desj I changed the repo to use a src structure. I can run the unittests, but running the demo gets me an error in ./src/tass/core/tass_files.py line 49. There's a path that's hardcoded ("tass/config/browsers.json") that seems to be throwing an error. I was wondering if we could change things to remove the hardcoded path?

**Comment by ty-desj** [comment]
@DominicParent that was the plan, that file is just for the default browser configurations to make testing/running the demos a little simpler. 

What I would like to have is possibly have a 'hard-coded' default browser configuration and then allowing users to attach a set of specific configurations when running tests. Do you think that we need to have a default configuration to fall back to in case of incorrectly or missing configurations when a test is run? I think we can open a new issue to track whatever change we end up making for browser configurations.

**Comment by DominicParent** [comment]
Python package is built using `python -m build`.
