### ISSUE TITLE
Default Browser Configuration

### ISSUE THREAD

**Issue by DominicParent** [StatCan/tass-ssat#58]
As per our discussion in #50, this issue is to decide and track what to do about default browser configurations.

**Comment by DominicParent** [comment]
Following a conversation on Teams, there's an agreement that there should be some sort of default browser configuration. In addition, the test_case, test_suite and test_run config files should have optional parameters to override higher level preferences. Highest level would be default, then test_run, test_suite, and then test_case.

**Comment by ty-desj** [comment]
Config parser does not fully meet requirements for more complex use cases.

**Comment by ty-desj** [comment]
Currently no plans to change implementation.
